"""empty message

Revision ID: 30e3f59342a9
Revises: d50bfb70a76a
Create Date: 2025-08-10 17:58:57.924482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e3f59342a9'
down_revision: Union[str, Sequence[str], None] = 'd50bfb70a76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Books', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Books', type_='foreignkey')
    # ### end Alembic commands ###
